import { IClient } from '../interfaces/table/IClient';

import sulfIcon from '../assets/icons/tables/sulf.svg';

export const mockClientData: IClient[] = [
  {
    name: 'FUNAPE',
    code: '',
    store: '0001',
    cnpj: '94813102001737',
    city: 'GOIANIA',
    uf: 'GO',
    preventiveDate: '20/10/2023',
    item: 'Contador Automático de Partículas para Líquidos SBSS',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000010',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000011',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000012',
      },
    ],
  },
  {
    name: 'FCA - SEDE',
    code: '',    
    store: '0001',    
    cnpj: '45985371000108',
    city: 'DIVINOPOLIS',
    uf: 'MG',
    preventiveDate: '25/10/2023',
    item: 'Spectro-M/C/R-W',
    status: 'Pausa por 5 dias',
    modality: 'Corretiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000001',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000002',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000003',
      },
    ],
  },
  {
    name: 'QUAKER - MAUA',
    code: '',     
    store: '0001',    
	cnpj: '03887324000696',
    city: 'MAUA',
    uf: 'SP',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Pausa por 10 dias',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },
  {
    name: 'MOINHO SETE IRMAOS LTDA',
    code: '',     
    store: '0001',    
	cnpj: '03410553000100',    
    city: 'UBERLANDIA',
    uf: 'MG',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Pausa por 10 dias',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },
  {
    name: 'LUBRIN',
    cnpj: '11989750000154',
    code: '',    
    store: '0001',    
    city: 'BARUERI',
    uf: 'SP',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'TEQUALY',
    code: '',    
    store: '0001',    
	cnpj: '61278875000306',
    city: 'CURITIBA',
    uf: 'PR',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'AMSPEC BRASIL INSPECOES TECNICAS',
    code: '',    
    store: '0001',    
	cnpj: '05642544000170',
    city: 'RIO DE JANEIRO',
    uf: 'RJ',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'UNAX - MACAE / RJ',
    code: '',    
    store: '0001',    
	cnpj: '04722574000124',
    city: 'MACAE',
    uf: 'RJ',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'ITALAC',
    code: '',    
    store: '0001',    
	cnpj: '61074829000123',
    city: 'CORUMBAIA',
    uf: 'GO',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'INT - INSTITUTO NACIONAL DE TECNOLOGIA',
    code: '',    
    store: '0001',    
	cnpj: '61074829001103',
    city: 'RIO DE JANEIRO',
    uf: 'RJ',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'DISTRIBUIDORA CHARRUA',
    code: '',    
    store: '0001',    
	cnpj: '05439635000103',
    city: 'LAJEADO',
    uf: 'RS',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'PENSALAB',
    code: '',    
    store: '0001',    
	cnpj: '60659463003107',
    city: 'SAO PAULO',
    uf: 'SP',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'COPAPE PRODUTOS DE PETROLEO',
    code: '',    
    store: '0001',    
	cnpj: '01663201000131',
    city: 'GUARULHOS, SP',
    uf: '',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'ONESUBSEA - IMBOASSICA / RJ',
    code: '',    
    store: '0001',    
	cnpj: '03887324002206',
    city: 'MACAE',
    uf: 'RJ',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'ASA INDUSTRIA E COMERCIO LTDA',
    code: '',    
    store: '0001',    
	cnpj: '03887324002478',
    city: 'BELO JARDIM',
    uf: 'PE',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'BRASAL REFRIGERANTES S/A',
    code: '',    
    store: '0001',    
	cnpj: '03887324002125',
    city: 'BRASILIA',
    uf: 'DF',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },{
    name: 'MOINHO DE TRIGO JM',
    code: '',    
    store: '0001',    
	cnpj: '03887324000181',
    city: 'LIZANIA',
    uf: 'GO',
    preventiveDate: '26/10/2023',
    item: 'Multi Viscosímetro HVM 472 Automático',
    status: 'Atendido',
    modality: 'Preventiva',
    parks: [
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000021',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000022',
      },
      {
        icon: sulfIcon,
        name: 'Banho Circulador Modelo TLV40-11 para baixas temperaturas',
        serialNumber: 'S/N: 000X0X0000023',
      },
    ],
  },
];
